# Generated by Django 5.1.6 on 2025-03-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adotante')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('abrigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abrigo')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adotante')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('abrigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abrigo')),
            ],
        ),
        migrations.AddField(
            model_name='adotante',
            name='historico_adocoes',
            field=models.ManyToManyField(through='core.Adocao', to='core.animal'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal'),
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('abrigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abrigo')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adotante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='core.abrigo')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='core.adotante')),
            ],
        ),
    ]
